export const genres = [
  'Action & Adventure',
  'Biography & Autobiography',
  'Business & Economics',
  'Graphic Novels',
  'Classics',
  'Crime',
  'Drama',
  'Dystopian',
  'Fantasy',
  'Fiction',
  'History',
  'Historical',
  'Humorous',
  'Journalism',
  'Juvenile Fiction',
  'Literary',
  'Music',
  'Mystery & Detective',
  'Philosophy',
  'Psychological',
  'Romance',
  'Science',
  'Self Help',
  'Science Fiction',
  'Social Themes',
  'Suspense',
  'Survival Stories',
  'Thrillers',
  'Travel',
  'Visionary & Metaphysical',
  'Women',
  'Young Adult Fiction',
];

