export const genres = [
  'Action & Adventure',
  'Art',
  'Biography & Autobiography',
  'Business & Economics',
  'Graphic Novels',
  'Computers',
  'Cooking',
  'Contemporary',
  'Design',
  'Drama',
  'Dystopian',
  'Education',
  'Fiction',
  'Games & Activities',
  'Gardening',
  'General',
  'Health & Fitness',
  'History',
  'House & Home',
  'Humorous',
  'Law',
  'Mathematics',
  'Medical',
  'Music',
  'Mystery & Detective',
  'Nature',
  'Performing Arts',
  'Philosophy',
  'Poetry',
  'Political Science',
  'Psychology',
  'Religion',
  'Romance',
  'Science',
  'Self Help',
  'Science Fiction',
  'Social Themes',
  'Sports & Recreation',
  'Suspense',
  'Survival Stories',
  'Thrillers',
  'Travel',
  'True Crime',
  'Visionary & Metaphysical',
  'Young Adult Fiction',
];

// genres.forEach((genre) => {
//   const words = genre.split(' ');
//   for (let i = 0; i < words.length; i++) {
//     words[i] = words[i][0].toUpperCase() + words[i].substr(1);
//   }
//   console.log(words.join(' '));
// });
