version: '3.8'

services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - '$DB_PORT:5432'
