name: GitHub Actions

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  test:

    name: Running Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install
    - run: npm install
    
  
    
